apiVersion: eaas.envmgmt.io/v1
kind: ConfigContext
metadata:
  name: rafay-aws-arun-first-project
  project: arun-first-project
spec:
  envs:
  - key: AWS_ACCESS_KEY_ID
    options:
      mask: true
    sensitive: true
    value: sealed://AWS_ACCESS_KEY_ID.
  - key: AWS_SECRET_ACCESS_KEY
    options:
      mask: true
    sensitive: true
    value: sealed://AWS_SECRET_ACCESS_KEY.
  secret:
    name: file://artifacts/rafay-aws-arun-first-project/sealed-secret.yaml
