apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: arun-github
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBxfzytypABZ8UxC7rmoUgcb0IgngRahHc58x23nCWuATajlFMw3VpPBVuUmoTkt5LuxaScs5OECb30JlHGx4NgiTqbpCVU3cS6//1ZfvfK5n67cyG8wJHkph5Q6xSdn3o2nZfhsGa9ktmVttYQmvs7fLBBIIhT+eMu9jvPtyaMVxGiLDViX2GO9KIGEn/TR+bF4SZO04p2lAg/09EnOyT+xeqTT9g4FMKBD2K0uJ1cYYuBy1jPdJYq9nihl0W4oyd18xLoYlzEjG8BFa3Qo+95wnklU4skzPo4JGP0HOsKeYAHJQ9oQgfJq54xsi10IqpsNyD7sa4I0ngzZknvNxXGB36pK6yiidFkVoFRmkuxohPqjll8e7lTDDpaXvOiOj3u6/PScvLVEnZflVRqJpR6mTKl/HzcOqK5+uYov50IXpkhTKGFDBDjhnBceBTmTAavJrBmkDZ5NQa+xaGX+1V8//UPV6RSc2LeXYy0fw==
  template:
    metadata:
      creationTimestamp: null
      name: arun-github
      namespace: default

