apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rafay-aws-arun-first-project
  namespace: default
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID.: AQByckfrf0enVoXXTNTNy8ZD6auauAizuiFFzr7fEZSzo46oByPiEkKXVt+oMUUfpoJ55C/zySxnEXqqDv7RSfC+EgL6FVDTzERurZco5acLy5PaV06+XGkFJlSoznxKShnHOwAMSyLCo0/VWBAhGMvQhMDUTOpcaMvij/l6zMHL6KZOQ8IF/1vspPX+yHKeF834UesM34sawRYJMWi4j1FPdRnT+r8ucNvBd/aMrm3aj4bU8LcVS4y1X5yH4Mkilna3z3MgnwxcBpOTFQvl8afrECyTJufh/Z/At5/QFebMO2XQB+liJyvQTKHMVN1OjWUl3P/gBwM31G6r5F5UxmneBlRpum2bHc+JdK/BdB5NlQibecb9t6TfNUaqLQ==
    AWS_SECRET_ACCESS_KEY.: AQBxpa0WkVXYZfwy63Vp9fhVCa7ksaHAbPmG00N4s938asYcpdyUop3/h008/R8VwcxnuC7YDfhxtE3qs+MGjm8x2L4b0fB+sB8YUbGXXVEarVXR5gh4pDu0IcRS2wvo7nbKmWVRU6BBeMklm1IAor2qPHS3VSnmUMw8TSUniPmYGbU5IjLHSqLx9uw5Xl+ERTSt9jIz6RFdxzrip54fHeI7rAD9nCd+/10cf2tTnPr7FhEpc5qKfB8U+qLr+YqbtxhPl7m2zLSK7Qfmg7C3ZHJESilS4JF4szk9vQ+5YF+BvRSxpwYVinEEbp6K/kiuwLx+DGiDbjAkTsZ5/mUKNmYGJwJtk9y5oQwS+Ij7aJqg1afKEoN5KpP6m73N8w==
  template:
    metadata:
      creationTimestamp: null
      name: rafay-aws-arun-first-project
      namespace: default

