apiVersion: integrations.k8smgmt.io/v3
kind: Repository
metadata:
  name: eaas-repo-arun-first-project
  project: arun-first-project
spec:
  agents:
  - name: eaas-agent
  credentials:
    password: sealed://credentials.password
    username: rathnaarun77
  endpoint: https://github.com/rathnaarun77/rafay-envmgr-test.git
  options: {}
  secret:
    name: file://artifacts/eaas-repo-arun-first-project/sealed-secret.yaml
  type: Git
