apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: eaas-repo-arun-first-project
  namespace: default
spec:
  encryptedData:
    credentials.password: AQBJnuKKDp6MzckswBE/NP8KeZE8EjsFBUpnlYg9cVcmEUAabRoF/Aq411yWJ4p9fHS6ghoSOKQ2YJngu5OwhFzCAOIVlXdeun/yaMDECBFlsUAlBRrAf2phpdguhUmUryariF5LCW3YE0zqOK/dPpeL+DuMO6/ywMtIqvcgxOIZ13vSK3irzkiLzSeTP0A4YWpMyS6JYhn6NIGlenQ/ah/ZMq6W9M1qYj0jksmUcOVATuXwXNVK3M1bGduHlWjvqGpawr8ZjI0JW/qikaHWCWfnI3mBuV3HQpSRsBCpoo9KzY1+6ZETVwkS8wz7MFJ0NuWLb4IIXk59Bf6IHXB1gLRs1/RZNoHhjVAF6/frlWUBgB4IdS0K/jmlpNoGukJe6MkzelIQ1Wj3YEJp+FdIkUmhww9i7j4PNnk=
  template:
    metadata:
      creationTimestamp: null
      name: eaas-repo-arun-first-project
      namespace: default

