apiVersion: eaas.envmgmt.io/v1
kind: Environment
metadata:
  name: arun-environment-test-1
  project: arun-first-project
spec:
  template:
    name: arun-env-1
    version: v1
    versionState: unspecified
